CREATE TABLE USER_LOGIN (
  USER_LOGIN_ID int(32) NOT NULL AUTO_INCREMENT,
  EMAIL_ID varchar(50) NOT NULL,
  PASSWORD varchar(512) NOT NULL,
  NAME varchar(50) NOT NULL,
  MOBILE_NUMBER varchar(20) NOT NULL,
  CREATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_UPDATED_DATE TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
  LANGUAGE varchar(15) DEFAULT NULL,
  ACCT_VERIFIED bit(1) NOT NULL DEFAULT b'0',
  EMAIL_VERIF_CODE varchar(32) DEFAULT NULL,
  MOBILE_VERIF_CODE varchar(6) DEFAULT NULL,
  PWD_RESET_ENABLED bit(1) NOT NULL DEFAULT b'0',
  COUNTRY_CODE int(3) NOT NULL,
  PRIMARY KEY (USER_LOGIN_ID),
  UNIQUE KEY EMAIL_ID_UNIQUE (EMAIL_ID),
  UNIQUE KEY USER_LOGIN_ID_UNIQUE (USER_LOGIN_ID),
  KEY EMAIL_MOB_VERIF_IDX (EMAIL_ID,MOBILE_VERIF_CODE),
  KEY EMAIL_EMAILVERIF_IDX (EMAIL_ID,EMAIL_VERIF_CODE),
  KEY EMAIL_PWD_IDX (EMAIL_ID,PASSWORD)
)
ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8
COMMENT='THIS IS THE TABLE WHERE ALL THE USER REGISTERED DETAILS ARE STORED';

